kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nodered-data
  namespace: nodered
  annotations:
    volume.beta.kubernetes.io/storage-class: "example-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
