apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodered
  namespace: nodered
spec:
  rules:
  - host: nodered.internal.local.com
    http:
      paths:
      - path: /
        backend:
          service:
            name: nodered
            port:
              number: 1880
